export const SET_GAME_BOARD_READY = "Game_Board_Ready";
export const CELL_CHANGE = "CELL_CHANGE";
export const CELL_SELECTED = "CELL_SELECTED";
export const NEW_GAME = "NEW_GAME";
export const SET_DIFFICULTY = "SET_DIFFICULTY";
export const TOGGLE_NOTE_VISIBILITY = "TOGGLE_NOTE_VISIBILITY";
export const HANDLE_CELL_SELECTED_HIGHLIGHT = "HANDLE_CELL_SELECTED_HIGHLIGHT";
export const TOGGLE_CELL_EDITING = "TOGGLE_CELL_EDITING";
